In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
involved_markers_heb_ta = pd.read_csv('./csv_tables/involved_markers_heb_ta.csv')
involved_markers_heb_ta

C:\Users\itay8\AppData\Local\Temp\ipykernel_11392\1779293570.py:1: DtypeWarning: Columns (45,152) have mixed types. Specify dtype option on import or set low_memory=False.
  involved_markers_heb_ta = pd.read_csv('./csv_tables/involved_markers_heb_ta.csv')

,Unnamed: 0,accident_id,provider_and_id,provider_code,file_type_police,involved_type,involved_type_hebrew,license_acquiring_date,age_group,age_group_hebrew,...,vehicle_status,vehicle_status_hebrew,vehicle_attribution,vehicle_attribution_hebrew,seats,total_weight,total_weight_hebrew,vehicle_damage,vehicle_damage_hebrew,accident_date
0,0,2013001938,12013001938,1,1,1,נהג,1996,8,35-39,...,0.0,NaN,1.0,ישראלי,99.0,1.0,עד 1.9,1.0,קל,2013-07-31 02:00:00
1,1,2013001938,12013001938,1,1,3,נפגע,0,5,20-24,...,0.0,NaN,1.0,ישראלי,99.0,1.0,עד 1.9,1.0,קל,2013-07-31 02:00:00
2,2,2013002190,12013002190,1,1,1,נהג,0,99,לא ידוע,...,0.0,NaN,0.0,לא מנועי,99.0,0.0,לא ידוע,4.0,אין נזק,2013-03-14 02:30:00
3,3,2013002190,12013002190,1,1,1,נהג,0,99,לא ידוע,...,0.0,NaN,1.0,ישראלי,3.0,1.0,עד 1.9,4.0,אין נזק,2013-03-14 02:30:00
4,4,2023065778,32023065778,3,3,1,נהג,0,99,לא ידוע,...,0.0,NaN,1.0,ישראלי,3.0,2.0,2.0-2.9,4.0,אין נזק,2023-01-05 14:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103058,103058,2023093433,32023093433,3,3,2,נהג נפגע,0,99,לא ידוע,...,0.0,NaN,1.0,ישראלי,99.0,0.0,לא ידוע,4.0,אין נזק,2023-02-14 08:30:00
103059,103059,2023099292,32023099292,3,3,1,נהג,2001,9,40-44,...,0.0,NaN,1.0,ישראלי,3.0,1.0,עד 1.9,4.0,אין נזק,2023-02-23 17:00:00
103060,103060,2023092779,32023092779,3,3,1,נהג,0,99,לא ידוע,...,0.0,NaN,1.0,ישראלי,99.0,0.0,לא ידוע,1.0,קל,2023-01-24 23:15:00
103061,103061,2023090298,32023090298,3,3,2,נהג נפגע,1995,10,45-49,...,0.0,NaN,1.0,ישראלי,3.0,1.0,עד 1.9,1.0,קל,2023-01-01 16:00:00
103062,103062,2023091245,32023091245,3,3,2,נהג נפגע,2010,7,30-34,...,0.0,NaN,1.0,ישראלי,99.0,0.0,לא ידוע,4.0,אין נזק,2023-03-05 20:30:00

In [21]:
# involved_markers_heb_ta = involved_markers_heb[involved_markers_heb.accident_yishuv_symbol == 5000]
# involved_markers_heb_ta

In [4]:
# involved_markers_heb_ta.drop(columns=['Unnamed: 0'],inplace=True)

In [5]:
# involved_markers_heb_ta.to_csv('./csv_tables/involved_markers_heb_ta.csv', index=False)

In [9]:
# involved_markers_heb_ta.drop(columns=['Unnamed: 0'],inplace=True)

In [22]:
involved_markers_heb_ta.columns.to_list()

['accident_id',
 'provider_and_id',
 'provider_code',
 'file_type_police',
 'involved_type',
 'involved_type_hebrew',
 'license_acquiring_date',
 'age_group',
 'age_group_hebrew',
 'sex',
 'sex_hebrew',
 'involve_vehicle_type',
 'involve_vehicle_type_hebrew',
 'safety_measures',
 'safety_measures_hebrew',
 'involve_yishuv_symbol',
 'involve_yishuv_name',
 'injury_severity',
 'injury_severity_hebrew',
 'injured_type',
 'injured_type_hebrew',
 'injured_position',
 'injured_position_hebrew',
 'population_type',
 'population_type_hebrew',
 'involve_home_region',
 'involve_home_region_hebrew',
 'involve_home_district',
 'involve_home_district_hebrew',
 'involve_home_natural_area',
 'involve_home_natural_area_hebrew',
 'involve_home_municipal_status',
 'involve_home_municipal_status_hebrew',
 'involve_home_yishuv_shape',
 'involve_home_yishuv_shape_hebrew',
 'hospital_time',
 'hospital_time_hebrew',
 'medical_type',
 'medical_type_hebrew',
 'release_dest',
 'release_dest_hebrew',
 'safety_measures_use',
 'safety_measures_use_hebrew',
 'late_deceased',
 'late_deceased_hebrew',
 'car_id',
 'involve_id',
 'accident_year',
 'accident_month',
 'provider_code_hebrew',
 'accident_timestamp',
 'accident_type',
 'accident_type_hebrew',
 'accident_severity',
 'accident_severity_hebrew',
 'location_accuracy',
 'location_accuracy_hebrew',
 'road_type',
 'road_type_hebrew',
 'road_shape',
 'road_shape_hebrew',
 'day_type',
 'day_type_hebrew',
 'police_unit',
 'police_unit_hebrew',
 'one_lane',
 'one_lane_hebrew',
 'multi_lane',
 'multi_lane_hebrew',
 'speed_limit',
 'speed_limit_hebrew',
 'road_intactness',
 'road_intactness_hebrew',
 'road_width',
 'road_width_hebrew',
 'road_sign',
 'road_sign_hebrew',
 'road_light',
 'road_light_hebrew',
 'road_control',
 'road_control_hebrew',
 'weather',
 'weather_hebrew',
 'road_surface',
 'road_surface_hebrew',
 'road_object',
 'road_object_hebrew',
 'object_distance',
 'object_distance_hebrew',
 'didnt_cross',
 'didnt_cross_hebrew',
 'cross_mode',
 'cross_mode_hebrew',
 'cross_location',
 'cross_location_hebrew',
 'cross_direction',
 'cross_direction_hebrew',
 'road1',
 'road2',
 'km',
 'km_raw',
 'km_accurate',
 'road_segment_id',
 'road_segment_number',
 'road_segment_name',
 'road_segment_from_km',
 'road_segment_to_km',
 'road_segment_length_km',
 'accident_yishuv_symbol',
 'accident_yishuv_name',
 'geo_area',
 'geo_area_hebrew',
 'day_night',
 'day_night_hebrew',
 'day_in_week',
 'day_in_week_hebrew',
 'traffic_light',
 'traffic_light_hebrew',
 'accident_region',
 'accident_region_hebrew',
 'accident_district',
 'accident_district_hebrew',
 'accident_natural_area',
 'accident_natural_area_hebrew',
 'accident_municipal_status',
 'accident_municipal_status_hebrew',
 'accident_yishuv_shape',
 'accident_yishuv_shape_hebrew',
 'street1',
 'street1_hebrew',
 'street2',
 'street2_hebrew',
 'non_urban_intersection',
 'non_urban_intersection_hebrew',
 'non_urban_intersection_by_junction_number',
 'accident_day',
 'accident_hour_raw',
 'accident_hour_raw_hebrew',
 'accident_hour',
 'accident_minute',
 'geom',
 'longitude',
 'latitude',
 'x',
 'y',
 'engine_volume',
 'engine_volume_hebrew',
 'manufacturing_year',
 'driving_directions',
 'driving_directions_hebrew',
 'vehicle_status',
 'vehicle_status_hebrew',
 'vehicle_attribution',
 'vehicle_attribution_hebrew',
 'seats',
 'total_weight',
 'total_weight_hebrew',
 'vehicle_vehicle_type',
 'vehicle_vehicle_type_hebrew',
 'vehicle_damage',
 'vehicle_damage_hebrew']

In [23]:
involved_markers_heb_ta.columns[involved_markers_heb_ta.columns.str.contains('vehicle')]

Index(['involve_vehicle_type', 'involve_vehicle_type_hebrew', 'vehicle_status',
       'vehicle_status_hebrew', 'vehicle_attribution',
       'vehicle_attribution_hebrew', 'vehicle_vehicle_type',
       'vehicle_vehicle_type_hebrew', 'vehicle_damage',
       'vehicle_damage_hebrew'],
      dtype='object')

In [24]:
involved_markers_heb_ta[['involve_vehicle_type', 'involve_vehicle_type_hebrew', 'vehicle_status',
       'vehicle_status_hebrew', 'vehicle_attribution',
       'vehicle_attribution_hebrew', 'vehicle_damage',
       'vehicle_damage_hebrew']]

,involve_vehicle_type,involve_vehicle_type_hebrew,vehicle_status,vehicle_status_hebrew,vehicle_attribution,vehicle_attribution_hebrew,vehicle_damage,vehicle_damage_hebrew
0,1.0,רכב נוסעים פרטי,0.0,NaN,1.0,ישראלי,1.0,קל
1,1.0,רכב נוסעים פרטי,0.0,NaN,1.0,ישראלי,1.0,קל
2,17.0,אחר ולא ידוע,0.0,NaN,0.0,לא מנועי,4.0,אין נזק
3,2.0,משא עד 3.5 טון - אחוד (טרנזיט),0.0,NaN,1.0,ישראלי,4.0,אין נזק
4,2.0,משא עד 3.5 טון - אחוד (טרנזיט),0.0,NaN,1.0,ישראלי,4.0,אין נזק
...,...,...,...,...,...,...,...,...
103058,8.0,"אופנוע עד 50 סמ""ק",0.0,NaN,1.0,ישראלי,4.0,אין נזק
103059,1.0,רכב נוסעים פרטי,0.0,NaN,1.0,ישראלי,4.0,אין נזק
103060,17.0,אחר ולא ידוע,0.0,NaN,1.0,ישראלי,1.0,קל
103061,1.0,רכב נוסעים פרטי,0.0,NaN,1.0,ישראלי,1.0,קל
103062,21.0,קורקינט חשמלי,0.0,NaN,1.0,ישראלי,4.0,אין נזק

### Exploring na values in vehicle
We have 2 columns with the same values:
* involve_vehicle_type
* vehicle_vehicle_type

Another 2 with the same values:
* vehicle_vehicle_type_hebrew
* involve_vehicle_type_hebrew

In order to take care of NA values I first need to make sure they all have the same rows with NA.

In [25]:
vehicle_type_na_idx = involved_markers_heb_ta['involve_vehicle_type'][involved_markers_heb_ta['involve_vehicle_type'].isna()].index
vehicle_type_na_idx

Int64Index([     7,     10,     29,     35,     37,     57,     69,     70,
                99,    108,
            ...
            102804, 102815, 102819, 102838, 102847, 102852, 102866, 102951,
            102998, 103053],
           dtype='int64', length=6675)

In [26]:
involved_markers_heb_ta.loc[vehicle_type_na_idx,'involve_vehicle_type_hebrew'].isna().sum()

6675

### Dropping duplicated columns

In [29]:
# involved_markers_heb_ta.drop(columns=['vehicle_vehicle_type', 'vehicle_vehicle_type_hebrew'], inplace=True)

In [30]:
# involved_markers_heb_ta.to_csv('./csv_tables/involved_markers_heb_ta.csv', index=False)

### Create date column

In [31]:
# Convert columns to string type
involved_markers_heb_ta['accident_year'] = involved_markers_heb_ta['accident_year'].astype(str)
involved_markers_heb_ta['accident_month'] = involved_markers_heb_ta['accident_month'].astype(str).str.zfill(2)  # zero pad days, months, hours, and minutes
involved_markers_heb_ta['accident_day'] = involved_markers_heb_ta['accident_day'].astype(str).str.zfill(2)
involved_markers_heb_ta['accident_hour'] = involved_markers_heb_ta['accident_hour'].astype(str).str.zfill(2)
involved_markers_heb_ta['accident_minute'] = involved_markers_heb_ta['accident_minute'].astype(str).str.zfill(2)

# Create the new date column
involved_markers_heb_ta['accident_date'] = pd.to_datetime(
    involved_markers_heb_ta['accident_year'] + '-' + 
    involved_markers_heb_ta['accident_month'] + '-' + 
    involved_markers_heb_ta['accident_day'] + ' ' + 
    involved_markers_heb_ta['accident_hour'] + ':' + 
    involved_markers_heb_ta['accident_minute']
)

In [32]:
involved_markers_heb_ta.to_csv('./csv_tables/involved_markers_heb_ta.csv')

### All have the same NA rows Next lets replace NA with empty string in string columns

In [7]:
# involved_markers_heb_ta['involve_vehicle_type_hebrew'].fillna('', inplace=True)
# involved_markers_heb_ta['vehicle_vehicle_type_hebrew'].fillna('', inplace=True)

In [9]:
# import plotly.express as px

# # Assuming your involved_markers_heb_ta DataFrame is already defined

# # Group by vehicle_vehicle_type_hebrew and count the occurrences
# vehicle_counts = involved_markers_heb_ta.groupby('vehicle_vehicle_type_hebrew').size().reset_index(name='counts')

# # Plotting using plotly
# fig = px.bar(vehicle_counts, x='vehicle_vehicle_type_hebrew', y='counts', title='Vehicle Type Counts')
# fig.show()